---
- name: configure webserver
  hosts: webservers
  become: true
  tasks:

  - name: Ensure installed package httpd and firewalld
    ansible.builtin.dnf:
      name: "{{ item }}"
    loop:
      - httpd
      - firewalld

  - name: Asegúrese de que se habilite y se inicie el servicio firewalld
    ansible.builtin.service:
      name: firewalld
      state: started
      enabled: true

  - name: Asegúrese de que se habilite y se inicie el servicio httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true


  - name: Asegurarse del contenido web
    ansible.builtin.copy:
      dest: /var/www/html/index.html
      content: "Welcome to the example.com intranet!\n"
...
